server:
  port: 9192

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hoteldb_test
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
